### ISSUE TITLE
Which of these users are known to be bots?

### ISSUE THREAD

**Issue by JesseTG** [alexpgates/twitter-block-list#1]
I'm working on a project involving detecting bots, which means I will need to gather a bunch of tweets from users *known* to be bots.

However, are these users necessarily bots?  Or are they just annoying people?  I ask because in my project, I'm explicitly looking for *bots* or *paid sockpuppets* while **not** trying to single out garden-variety assholes.

**Comment by alexpgates** [comment]
This is a mixture. A lot of them are definitely bots, but there are plenty of garden-variety assholes in here, too.
It's fairly easy to spot a pattern of accounts that appear to be mass-created.. example: joey1846394621 or whatever (name+random 5+ digit number) - but even then, it's hard to say if the posts behind those are bots or if they're just farmed out to people to use.
This list was entirely built by me manually blocking people on Twitter, so it's not going to be a good resource for your project. 
I am interested to see what you come up with, though!

**Comment by JesseTG** [comment]
Might be useful for a test data set, at least.  Also, forgot to mention that I'm also looking for sock puppets (i.e. not necessarily bots per se but people hired to stir the pot). Thank you!
